/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ferreteria.presentacion.view;

import ferreteria.Application;
import ferreteria.Session;
import ferreteria.entities.Empleado;
import ferreteria.presentacion.controller.ApplicationController;
import ferreteria.presentacion.model.ApplicationModel;
import java.util.Arrays;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JInternalFrame;

/**
 *
 * @author luisalejandro
 */
public class ApplicationView extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form ApplicationView
     */
    public ApplicationView() {
        initComponents();
        this.setSize(this.getMaximumSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        f01menu = new javax.swing.JMenu();
        f01menuitem = new javax.swing.JMenuItem();
        f02menu = new javax.swing.JMenu();
        f02menuitem = new javax.swing.JMenuItem();
        f03menu = new javax.swing.JMenu();
        f03menuitem = new javax.swing.JMenuItem();
        f04menu = new javax.swing.JMenu();
        f04menuitem = new javax.swing.JMenuItem();
        f05menu = new javax.swing.JMenu();
        f5menuitem = new javax.swing.JMenuItem();
        f06menu = new javax.swing.JMenu();
        f06menuitem = new javax.swing.JMenuItem();
        f07menu = new javax.swing.JMenu();
        helpmenu = new javax.swing.JMenu();
        aboutmenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        desktopPane.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(desktopPane);

        f01menu.setText("F-01");
        f01menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f01menuActionPerformed(evt);
            }
        });

        f01menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        f01menuitem.setText("F-01");
        f01menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f01menuitemActionPerformed(evt);
            }
        });
        f01menu.add(f01menuitem);

        jMenuBar1.add(f01menu);

        f02menu.setText("F-02");
        f02menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f02menuActionPerformed(evt);
            }
        });

        f02menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        f02menuitem.setText("F-02");
        f02menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f02menuitemActionPerformed(evt);
            }
        });
        f02menu.add(f02menuitem);

        jMenuBar1.add(f02menu);

        f03menu.setText("F-03");

        f03menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        f03menuitem.setText("F-03");
        f03menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f03menuitemActionPerformed(evt);
            }
        });
        f03menuitem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                f03menuitemKeyPressed(evt);
            }
        });
        f03menu.add(f03menuitem);

        jMenuBar1.add(f03menu);

        f04menu.setText("F-04");
        f04menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f04menuActionPerformed(evt);
            }
        });

        f04menuitem.setText("F-04");
        f04menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f04menuitemActionPerformed(evt);
            }
        });
        f04menu.add(f04menuitem);

        jMenuBar1.add(f04menu);

        f05menu.setText("F-05");
        f05menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f05menuActionPerformed(evt);
            }
        });

        f5menuitem.setText("F-05");
        f5menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f5menuitemActionPerformed(evt);
            }
        });
        f05menu.add(f5menuitem);

        jMenuBar1.add(f05menu);

        f06menu.setText("F-06");
        f06menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f06menuActionPerformed(evt);
            }
        });

        f06menuitem.setText("F-06");
        f06menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f06menuitemActionPerformed(evt);
            }
        });
        f06menu.add(f06menuitem);

        jMenuBar1.add(f06menu);

        f07menu.setText("F-07");
        f07menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f07menuActionPerformed(evt);
            }
        });
        jMenuBar1.add(f07menu);

        helpmenu.setText("Help");
        helpmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpmenuActionPerformed(evt);
            }
        });

        aboutmenu.setText("About");
        aboutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutmenuActionPerformed(evt);
            }
        });
        helpmenu.add(aboutmenu);

        exitMenu.setText("Cerrar Sesion");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        helpmenu.add(exitMenu);

        jMenuBar1.add(helpmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f01menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f01menuActionPerformed
        Empleado principal = (Empleado) session.getAttribute(Application.USER_ATTRIBUTE);
        if ( Arrays.asList(Application.ROL_ADMINISTRADOR).contains(principal.getRol())){
            controller.mostrarProducto();
        }
        else{
            model.setMensaje(Application.ROL_NOTAUTHORIZED);
                       
        }
        
        
    }//GEN-LAST:event_f01menuActionPerformed

    private void f02menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f02menuActionPerformed
        
    }//GEN-LAST:event_f02menuActionPerformed

    private void f04menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f04menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f04menuActionPerformed

    private void f05menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f05menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f05menuActionPerformed

    private void f06menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f06menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f06menuActionPerformed

    private void f07menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f07menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f07menuActionPerformed

    private void helpmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpmenuActionPerformed
        
    }//GEN-LAST:event_helpmenuActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        this.controller.exit();
    }//GEN-LAST:event_exitMenuActionPerformed

    private void f01menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f01menuitemActionPerformed
      controller.mostrarProducto();
    }//GEN-LAST:event_f01menuitemActionPerformed

    private void f02menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f02menuitemActionPerformed
      controller.mostrarBodega();
    }//GEN-LAST:event_f02menuitemActionPerformed

    private void f03menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f03menuitemActionPerformed
        controller.mostrarEmpleado();
    }//GEN-LAST:event_f03menuitemActionPerformed

    private void f04menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f04menuitemActionPerformed
        controller.mostrarCliente();
    }//GEN-LAST:event_f04menuitemActionPerformed

    private void f03menuitemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f03menuitemKeyPressed
  
    }//GEN-LAST:event_f03menuitemKeyPressed

    private void f5menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f5menuitemActionPerformed
        controller.mostrarFactura();
    }//GEN-LAST:event_f5menuitemActionPerformed

    private void f06menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f06menuitemActionPerformed
        controller.mostrarFacturaPago();
    }//GEN-LAST:event_f06menuitemActionPerformed

    private void aboutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutmenuActionPerformed
        controller.about();
    }//GEN-LAST:event_aboutmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutmenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu f01menu;
    private javax.swing.JMenuItem f01menuitem;
    private javax.swing.JMenu f02menu;
    private javax.swing.JMenuItem f02menuitem;
    private javax.swing.JMenu f03menu;
    private javax.swing.JMenuItem f03menuitem;
    private javax.swing.JMenu f04menu;
    private javax.swing.JMenuItem f04menuitem;
    private javax.swing.JMenu f05menu;
    private javax.swing.JMenu f06menu;
    private javax.swing.JMenuItem f06menuitem;
    private javax.swing.JMenu f07menu;
    private javax.swing.JMenuItem f5menuitem;
    private javax.swing.JMenu helpmenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    ApplicationModel model;
    ApplicationController controller;
    Session session;

    public void setController(ApplicationController controller) {
        this.controller = controller;
    }

    public ApplicationController getController() {
        return controller;
    }

    public void setModel(ApplicationModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public ApplicationModel getModel() {
        return model;
    }
    
    public void addInternalFrame(JInternalFrame f){
       this.desktopPane.add(f);
   }
     
    @Override
    public void update(Observable o, Object arg) {
        if (model.getCurrent()!=null){
           this.setTitle("FERRETERIA ("+model.getCurrent().getIdEmpleado()+")");
       }
       else{
           this.setTitle("FERRETERIA");
       } 
    }
}
