/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ferreteria.presentacion.view;

import ferreteria.Application;
import ferreteria.presentacion.controller.FacturasController;
import ferreteria.presentacion.model.FacturasModel;
import java.util.Observer;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author luisalejandro
 */
public class FacturasView extends JInternalFrame implements Observer{
    
    FacturasModel model;
    FacturasController controller;

    public void setController(FacturasController controller) {
        this.controller = controller;
    }
    
    public FacturasController getController() {
        return controller;
    }

    public void setModel(FacturasModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public FacturasModel getModel() {
        return model;
    }
    
    @Override
   public void update(java.util.Observable updatedModel,Object parametros){
       facturaFld.setText(model.getFilter().getNumFactura());
       if (model.getErrores().get("facturaFld")!=null){
            facturaLbl.setBorder(Application.BORDER_ERROR);
            facturaLbl.setToolTipText(model.getErrores().get("nombreFld"));
        }
        else{
            facturaLbl.setBorder(null);
            facturaLbl.setToolTipText("");
        }
       
       facturasFld.setModel(model.getFacturas());
       this.revalidate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }      
   }
    /**
     * Creates new form PersonasView
     */
    public FacturasView() {
        super("",false,true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facturaLbl = new javax.swing.JLabel();
        facturaFld = new javax.swing.JTextField();
        buscarFacturaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        facturasFld = new javax.swing.JTable();
        borrarFld = new javax.swing.JButton();
        agregarFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("FACTURACION");

        facturaLbl.setText("Factura");

        buscarFacturaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/presentacion/icons/search.png"))); // NOI18N
        buscarFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFacturaBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 100));

        facturasFld.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        facturasFld.setRowHeight(25);
        facturasFld.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        facturasFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facturasFldMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(facturasFld);

        borrarFld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/presentacion/icons/images.png"))); // NOI18N
        borrarFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarFldActionPerformed(evt);
            }
        });

        agregarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/presentacion/icons/green-plus-sign-md_converted.png"))); // NOI18N
        agregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(facturaLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facturaFld, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(agregarFactura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarFacturaBtn)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facturaLbl)
                    .addComponent(facturaFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarFacturaBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(borrarFld)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFacturaBtnActionPerformed
      controller.buscar();
    }//GEN-LAST:event_buscarFacturaBtnActionPerformed

    private void facturasFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturasFldMouseClicked
     if (evt.getClickCount() == 2) {
        int row = this.facturasFld.getSelectedRow();
        Application.FACTURA_VIEW.setLocation(evt.getLocationOnScreen());
        controller.editar(row);
      } 
    }//GEN-LAST:event_facturasFldMouseClicked

    private void borrarFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarFldActionPerformed
        int row = this.facturasFld.getSelectedRow();
        controller.borrar(row);
    }//GEN-LAST:event_borrarFldActionPerformed

    private void agregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFacturaActionPerformed
        controller.preAgregar();
    }//GEN-LAST:event_agregarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturasView().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarFactura;
    private javax.swing.JButton borrarFld;
    private javax.swing.JButton buscarFacturaBtn;
    public javax.swing.JTextField facturaFld;
    private javax.swing.JLabel facturaLbl;
    public javax.swing.JTable facturasFld;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
