/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ferreteria.presentacion.view;

import com.itextpdf.text.DocumentException;
import ferreteria.Application;
import ferreteria.entities.Factura;
import ferreteria.entities.Lineas;
import ferreteria.presentacion.controller.FacturaController;
import ferreteria.presentacion.model.FacturaModel;
import ferreteria.presentacion.model.LineaTableModel;
import java.io.IOException;
import java.util.Arrays;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisalejandro
 */
public class FacturaView extends JDialog implements Observer {

    /**
     * Creates new form PersonaView
     */
    public FacturaView(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        this.setSize(this.getMaximumSize());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoFld = new javax.swing.ButtonGroup();
        numLbl = new javax.swing.JLabel();
        fechaLbl = new javax.swing.JLabel();
        horaLbl = new javax.swing.JLabel();
        estadoLbl = new javax.swing.JLabel();
        guardarFld = new javax.swing.JButton();
        cancelarFld = new javax.swing.JButton();
        numFld = new javax.swing.JTextField();
        fechaFld = new javax.swing.JTextField();
        estadoFldCancelada = new javax.swing.JCheckBox();
        estadoFldDespachada = new javax.swing.JCheckBox();
        horaFld = new javax.swing.JTextField();
        numFLbl = new javax.swing.JLabel();
        numFLabel = new javax.swing.JTextField();
        clienteLbl = new javax.swing.JLabel();
        clientecBox = new javax.swing.JComboBox();
        empleadoLbl = new javax.swing.JLabel();
        empleadocbox = new javax.swing.JComboBox();
        productoLbl = new javax.swing.JLabel();
        buscarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lineasFld = new javax.swing.JTable();
        borrarlineaBtn = new javax.swing.JButton();
        pagarBtn = new javax.swing.JButton();
        despacharBtn = new javax.swing.JButton();
        totalLbl = new javax.swing.JLabel();
        totalFld = new javax.swing.JTextField();

        setTitle("FACTURA");
        setIconImage(null);

        numLbl.setText("# de Factura");

        fechaLbl.setText("Fecha");

        horaLbl.setText("Hora");

        estadoLbl.setText("Estado ");

        guardarFld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/presentacion/icons/save.png"))); // NOI18N
        guardarFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarFldActionPerformed(evt);
            }
        });

        cancelarFld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/presentacion/icons/cancel.png"))); // NOI18N
        cancelarFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarFldActionPerformed(evt);
            }
        });

        estadoFldCancelada.setText("Cancelada");

        estadoFldDespachada.setText("Despachada");

        numFLbl.setText("Numero Ferreteria");

        clienteLbl.setText("Cliente");

        empleadoLbl.setText("ID Empleado");

        productoLbl.setText("Producto");

        buscarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/presentacion/icons/search.png"))); // NOI18N
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        lineasFld.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(lineasFld);

        borrarlineaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/presentacion/icons/images.png"))); // NOI18N
        borrarlineaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarlineaBtnActionPerformed(evt);
            }
        });

        pagarBtn.setText("PAGAR");
        pagarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarBtnActionPerformed(evt);
            }
        });

        despacharBtn.setText("DESPACHAR");

        totalLbl.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numLbl)
                            .addComponent(estadoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clienteLbl))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(estadoFldCancelada)
                                .addGap(28, 28, 28)
                                .addComponent(estadoFldDespachada)
                                .addGap(58, 58, 58)
                                .addComponent(numFLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(numFld, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fechaLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaFld, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horaLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horaFld, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(clientecBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(empleadoLbl)
                                .addGap(18, 18, 18)
                                .addComponent(empleadocbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(guardarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)
                                .addComponent(cancelarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(256, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(borrarlineaBtn)
                                            .addComponent(pagarBtn)
                                            .addComponent(despacharBtn)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(totalLbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(totalFld, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productoLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarButton)))
                        .addGap(0, 5, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numLbl)
                    .addComponent(numFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaLbl)
                    .addComponent(fechaFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaLbl)
                    .addComponent(horaFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLbl)
                    .addComponent(estadoFldCancelada)
                    .addComponent(estadoFldDespachada)
                    .addComponent(numFLbl)
                    .addComponent(numFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteLbl)
                    .addComponent(clientecBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleadoLbl)
                    .addComponent(empleadocbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productoLbl)
                    .addComponent(buscarButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(borrarlineaBtn)
                        .addGap(18, 18, 18)
                        .addComponent(pagarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(despacharBtn)
                        .addGap(18, 18, 18)
                        .addComponent(totalLbl)
                        .addGap(10, 10, 10)
                        .addComponent(totalFld, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardarFld)
                    .addComponent(cancelarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarFldActionPerformed
        controller.guardar();
    }//GEN-LAST:event_guardarFldActionPerformed

    private void cancelarFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarFldActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarFldActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        controller.buscar(ERROR);
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void borrarlineaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarlineaBtnActionPerformed
        int row = this.lineasFld.getSelectedRow();
        controller.borrar(row);
    }//GEN-LAST:event_borrarlineaBtnActionPerformed

    private void pagarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarBtnActionPerformed
        try {
            controller.pagar();
        } catch (DocumentException | IOException ex) {
            Logger.getLogger(FacturaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pagarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarlineaBtn;
    public javax.swing.JButton buscarButton;
    public javax.swing.JButton cancelarFld;
    private javax.swing.JLabel clienteLbl;
    public javax.swing.JComboBox clientecBox;
    private javax.swing.JButton despacharBtn;
    private javax.swing.JLabel empleadoLbl;
    public javax.swing.JComboBox empleadocbox;
    public javax.swing.JCheckBox estadoFldCancelada;
    public javax.swing.JCheckBox estadoFldDespachada;
    public javax.swing.JLabel estadoLbl;
    public javax.swing.JTextField fechaFld;
    public javax.swing.JLabel fechaLbl;
    public javax.swing.JButton guardarFld;
    public javax.swing.JTextField horaFld;
    public javax.swing.JLabel horaLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lineasFld;
    public javax.swing.JTextField numFLabel;
    private javax.swing.JLabel numFLbl;
    public javax.swing.JTextField numFld;
    public javax.swing.JLabel numLbl;
    private javax.swing.JButton pagarBtn;
    private javax.swing.JLabel productoLbl;
    private javax.swing.ButtonGroup sexoFld;
    public javax.swing.JTextField totalFld;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
    
    FacturaModel model;
    FacturaController controller;
   

    public void setController(FacturaController controller) {
        this.controller = controller;
    }

    public FacturaController getController() {
        return controller;
    }

    public void setModel(FacturaModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public FacturaModel getModel() {
        return model;
    }
    
    
    
    @Override
   public void update(Observable updatedModel,Object parametros){
       Factura facturaCurrent = model.getCurrent();
       this.numFld.setEnabled(model.getModo()==Application.MODO_AGREGAR);
       totalFld.setText(totalFld.getText()+model.getCurrent().calculaTotal());
       
       numFld.setText(facturaCurrent.getNumFactura());
       if (model.getErrores().get("num")!=null){
            numLbl.setBorder(Application.BORDER_ERROR);
            numLbl.setToolTipText(model.getErrores().get("num"));
        }
        else{
            numLbl.setBorder(null);
            numLbl.setToolTipText("");
        }
       
        Boolean editable = Arrays.asList(Application.MODO_AGREGAR, Application.MODO_EDITAR).contains(model.getModo());
   
        numFLabel.setText(facturaCurrent.getNumFerreteria());
       if (model.getErrores().get("num")!=null){
            numFLabel.setBorder(Application.BORDER_ERROR);
            numFLabel.setToolTipText(model.getErrores().get("num"));
        }
        else{
            numFLabel.setBorder(null);
            numFLabel.setToolTipText("");
        }
        
        horaFld.setEnabled(editable);
        horaFld.setText(facturaCurrent.getHora());
        if (model.getErrores().get("hora")!=null){
            horaLbl.setBorder(Application.BORDER_ERROR);
            horaLbl.setToolTipText(model.getErrores().get("hora"));
        }
        else{
           horaLbl.setBorder(null);
           horaLbl.setToolTipText("");
        }
        
        fechaFld.setEnabled(editable);
        fechaFld.setText(facturaCurrent.getFecha());
        if (model.getErrores().get("fecha")!=null){
            fechaLbl.setBorder(Application.BORDER_ERROR);
            fechaLbl.setToolTipText(model.getErrores().get("fecha"));
        }
        else{
           fechaLbl.setBorder(null);
           fechaLbl.setToolTipText("");
        }
        
        estadoFldCancelada.setEnabled(editable);
        estadoFldCancelada.setSelected(facturaCurrent.isCancelada());
        
        estadoFldDespachada.setEnabled(editable);
        estadoFldDespachada.setSelected(facturaCurrent.isDepachada());


        clientecBox.setEnabled(editable);
        clientecBox.setModel(model.getClientes());
        clientecBox.setSelectedItem(facturaCurrent.getIdCliente());
        
        empleadocbox.setEnabled(editable);
        empleadocbox.setModel(model.getEmpleados());
        empleadocbox.setSelectedItem(facturaCurrent.getIdEmpleado());
        
        guardarFld.setVisible(editable);
        lineasFld.setModel(model.getLineas());    
        
        this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
   }
}
