/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ferreteria.presentacion.view;

import java.util.Arrays;
import javax.swing.JOptionPane;
import ferreteria.Application;
import ferreteria.entities.Producto;
import ferreteria.presentacion.controller.ProductoController;
import ferreteria.presentacion.model.ProductoModel;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JDialog;
/**
 *
 * @author jsanchez
 */
public class ProductoView extends JDialog implements Observer {

    /**
     * Creates new form PersonaView
     */
    public ProductoView(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoFld = new javax.swing.ButtonGroup();
        codigoLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        precioLbl = new javax.swing.JLabel();
        cantidadLbl = new javax.swing.JLabel();
        guardarFld = new javax.swing.JButton();
        cancelarFld = new javax.swing.JButton();
        codigoFld = new javax.swing.JTextField();
        nombreFld = new javax.swing.JTextField();
        precioFld = new javax.swing.JTextField();
        cantidadFld = new javax.swing.JTextField();

        setTitle("PRODUCTO");
        setIconImage(null);

        codigoLbl.setText("Codigo");

        nombreLbl.setText("Nombre");

        precioLbl.setText("Precio");

        cantidadLbl.setText("Cantidad");

        guardarFld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/presentacion/icons/save.png"))); // NOI18N
        guardarFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarFldActionPerformed(evt);
            }
        });

        cancelarFld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/presentacion/icons/cancel.png"))); // NOI18N
        cancelarFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarFldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precioLbl)
                    .addComponent(nombreLbl)
                    .addComponent(codigoLbl)
                    .addComponent(cantidadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoFld, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreFld, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(cancelarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cantidadFld, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(precioFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLbl)
                    .addComponent(codigoFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLbl)
                    .addComponent(nombreFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioLbl)
                    .addComponent(precioFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadLbl)
                    .addComponent(cantidadFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardarFld)
                    .addComponent(cancelarFld, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarFldActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarFldActionPerformed

    private void guardarFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarFldActionPerformed
        this.controller.guardar();
    }//GEN-LAST:event_guardarFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelarFld;
    public javax.swing.JTextField cantidadFld;
    public javax.swing.JLabel cantidadLbl;
    public javax.swing.JTextField codigoFld;
    public javax.swing.JLabel codigoLbl;
    public javax.swing.JButton guardarFld;
    public javax.swing.JTextField nombreFld;
    public javax.swing.JLabel nombreLbl;
    public javax.swing.JTextField precioFld;
    public javax.swing.JLabel precioLbl;
    private javax.swing.ButtonGroup sexoFld;
    // End of variables declaration//GEN-END:variables
    
    ProductoController controller;
    ProductoModel model;

    public void setController(ProductoController controller) {
        this.controller = controller;
    }

    public ProductoController getController() {
        return controller;
    }
   
    public void setModel(ProductoModel model){
        this.model = model;
         model.addObserver(this);
    }

    public ProductoModel getModel() {
        return model;
    }
    
    @Override
   public void update(Observable o,Object arg){
       Producto productoCurrent = model.getCurrent();
        
       this.codigoFld.setEnabled(model.getModo()==Application.MODO_AGREGAR);
       
       codigoFld.setText(String.valueOf(productoCurrent.getCodigo()));
       if (model.getErrores().get("codigo")!=null){
            codigoLbl.setBorder(Application.BORDER_ERROR);
            codigoLbl.setToolTipText(model.getErrores().get("codigo"));
        }
        else{
            codigoLbl.setBorder(null);
            codigoLbl.setToolTipText("");
        }
       
        Boolean editable = Arrays.asList(Application.MODO_AGREGAR, Application.MODO_EDITAR).contains(model.getModo());
   
        nombreFld.setEnabled(editable);
        nombreFld.setText(productoCurrent.getNombreProducto());
        if (model.getErrores().get("nombreProducto")!=null){
            nombreLbl.setBorder(Application.BORDER_ERROR);
            nombreLbl.setToolTipText(model.getErrores().get("nombreProducto"));
        }
        else{
           nombreLbl.setBorder(null);
           nombreLbl.setToolTipText("");
        }

        precioFld.setEnabled(editable);
        precioFld.setText(String.valueOf(productoCurrent.getPrecio()));
        if (model.getErrores().get("precio")!=null){
            precioLbl.setBorder(Application.BORDER_ERROR);
            precioLbl.setToolTipText(model.getErrores().get("precio"));
        }
        else{
           precioLbl.setBorder(null);
           precioLbl.setToolTipText("");
        }
        
        cantidadFld.setEnabled(editable);
        cantidadFld.setText(String.valueOf(productoCurrent.getCantExistencias()));
        if (model.getErrores().get("cantExistencias")!=null){
            cantidadLbl.setBorder(Application.BORDER_ERROR);
            cantidadLbl.setToolTipText(model.getErrores().get("cantExistencias"));
        }
        else{
           cantidadLbl.setBorder(null);
           cantidadLbl.setToolTipText("");
        }
        
        guardarFld.setVisible(editable);
        
        this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
    } 
}
